one_hot编码定义  
在一个给定的向量中，按照设定的最值–可以是向量中包含的最大值（作为最高分类数），有也可以是自定义的最大值，设计one_hot编码的长度：最大值+1【详见举的例子吧】。

然后按照最大值创建一个1*(最大值+1)的维度大小的全零零向量：[0, 0, 0, …] => 共最大值+1对应的个数

接着按照向量中的值，从第0位开始索引，将向量中值对应的位置设置为1，其他保持为0.

总结：one_hot编码主要用于分类时，作为一个类别的编码–方便判别与相关计算；
【1. 如同类别数统计，只需要将one_hot编码相加得到一个一维向量就知道了一批数据中所有类别的预测或真实的分布情况；
2. 相比于预测出具体的类别数–43等，用向量可以使用向量相关的算法进行时间上的优化等等】
————————————————
版权声明：本文为CSDN博主「NULL not error」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/weixin_44604887/article/details/109523281


In [3]:
import torch.nn.functional as F
import torch
x = torch.tensor([5,3,4,5,1,2,])# 默认按照targets其中的最大值+1作为one_hot编码的长度

x1 = F.one_hot(x)
print(x1)

tensor([[0, 0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0]])


In [4]:
#指定one_hot编码长度
num = 7
target = F.one_hot(x,num_classes=num)
print(target)

tensor([[0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0]])


In [5]:
import torch
n =torch.zeros(1,2,3)
n.dim()

3

In [9]:

import torch
class_num = 5
label = torch.IntTensor([1,3,0]) 
# ones = torch.eye(class_num)
# ones.index_select(0,label)
target = torch.eye(class_num).index_select(dim=0, index=label)

In [10]:
target

tensor([[0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0.]])

In [12]:
import torch
import numpy as np

gt = np.random.randint(0,5, size=[15,15])  #先生成一个15*15的label，值在5以内，意思是5类分割任务
gt = torch.LongTensor(gt)



def get_one_hot(label, N):
    size = list(label.size())
    label = label.view(-1)   # reshape 为向量
    ones = torch.eye(N)
    ones = ones.index_select(0, label)   # 用上面的办法转为换one hot
    size.append(N)  # 把类别输目添到size的尾后，准备reshape回原来的尺寸
    return ones.view(*size)


gt_one_hot = get_one_hot(gt, 5)
print(gt_one_hot)
print(gt_one_hot.shape)

print(gt_one_hot.argmax(-1) == gt)  # 判断one hot 转换方式是否正确，全是1就是正确的


tensor([[[1., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 1., 0.],
         ...,
         [1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 1., 0., 0., 0.]],

        [[0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 1., 0.],
         ...,
         [1., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0.]],

        [[0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.],
         [0., 0., 0., 0., 1.],
         ...,
         [0., 0., 0., 1., 0.],
         [1., 0., 0., 0., 0.],
         [1., 0., 0., 0., 0.]],

        ...,

        [[0., 0., 1., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 1.],
         ...,
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 1.],
         [0., 1., 0., 0., 0.]],

        [[0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 1.],
         ...,
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.],
         