https://blog.csdn.net/liangjiu2009/article/details/107352164  
https://zhuanlan.zhihu.com/p/103426335#:~:text=Dice%20Loss%201%20Dice%E7%B3%BB%E6%95%B0%EF%BC%9A%E6%A0%B9%E6%8D%AE%20Lee%20Raymond%20Dice%20%5B1%5D%E5%91%BD%E4%BB%A4%EF%BC%8C%E6%98%AF%E7%94%A8%E6%9D%A5%E5%BA%A6%E9%87%8F%E9%9B%86%E5%90%88%E7%9B%B8%E4%BC%BC%E5%BA%A6%E7%9A%84%E5%BA%A6%E9%87%8F%E5%87%BD%E6%95%B0%EF%BC%8C%E9%80%9A%E5%B8%B8%E7%94%A8%E4%BA%8E%E8%AE%A1%E7%AE%97%E4%B8%A4%E4%B8%AA%E6%A0%B7%E6%9C%AC%E4%B9%8B%E9%97%B4%E7%9A%84%E5%83%8F%E7%B4%A0%EF%BC%8C%E5%85%AC%E5%BC%8F%E5%A6%82%E4%B8%8B%EF%BC%9A,Loss%E4%BD%BF%E7%94%A8%E4%B8%8E%E6%A0%B7%E6%9C%AC%E6%9E%81%E5%BA%A6%E4%B8%8D%E5%9D%87%E8%A1%A1%E7%9A%84%E6%83%85%E5%86%B5%EF%BC%8C%E5%A6%82%E6%9E%9C%E4%B8%80%E8%88%AC%E6%83%85%E5%86%B5%E4%B8%8B%E4%BD%BF%E7%94%A8Dice%20Loss%E4%BC%9A%E5%9B%9E%E5%8F%8D%E5%90%91%E4%BC%A0%E6%92%AD%E6%9C%89%E4%B8%8D%E5%88%A9%E7%9A%84%E5%BD%B1%E5%93%8D%EF%BC%8C%E4%BD%BF%E5%BE%97%E8%AE%AD%E7%BB%83%E4%B8%8D%E7%A8%B3%E5%AE%9A%E3%80%82%203%20%E8%AE%AD%E7%BB%83%E5%88%86%E5%89%B2%E7%BD%91%E7%BB%9C%EF%BC%8C%E4%BE%8B%E5%A6%82FCN%EF%BC%8CUNet%E6%98%AF%E9%80%89%E6%8B%A9%E4%BA%A4%E5%8F%89%E7%86%B5Loss%E8%BF%98%E6%98%AF%E9%80%89%E6%8B%A9Dice%20Loss%EF%BC%9F%20More%20items...%20  
https://zhuanlan.zhihu.com/p/349046748  
https://blog.csdn.net/baidu_36511315/article/details/105217674
https://blog.csdn.net/CaiDaoqing/article/details/90457197

In [75]:
import torch
import torch.nn as nn

class Diceloss2D(nn.Module):
    def __init__(self):
        super(Diceloss2D, self).__init__()

    def forward(self, input, targets):
        # 获取每个批次的大小 N
        N = targets.size()[0]
        # 平滑变量
        smooth = 1
        # 将宽高 reshape 到同一纬度
        input_flat = input.view(N, -1)
        targets_flat = targets.view(N, -1)

        # 计算交集
        intersection = input_flat * targets_flat 
        N_dice_eff = (2 * intersection.sum(1) + smooth) / (input_flat.sum(1) + targets_flat.sum(1) + smooth)
        print(f"N_dice_eff{N_dice_eff}")
        # 计算一个批次中平均每张图的损失
        loss = 1 - N_dice_eff.sum() / N
        return loss


In [76]:
x = torch.randn(4,3)
print(x)

tensor([[ 1.0007,  1.7434,  1.1501],
        [-1.1193, -0.9224, -0.1627],
        [-0.0555,  0.1877,  1.7602],
        [ 0.0107, -0.4988,  0.8969]])


In [77]:
y = torch.randint(0,2,size=(4,3))
y

tensor([[1, 1, 0],
        [0, 1, 0],
        [0, 0, 0],
        [1, 0, 1]])

In [78]:
x1 =x.sum()
x1

tensor(3.9910)

In [79]:
t= x*y
t

tensor([[ 1.0007,  1.7434,  0.0000],
        [-0.0000, -0.9224, -0.0000],
        [-0.0000,  0.0000,  0.0000],
        [ 0.0107, -0.0000,  0.8969]])

In [80]:
t1 = t.sum()
t1

tensor(2.7292)

In [81]:
y1=y.sum()
y1

tensor(5)

In [82]:
D = (2*t1+1)/(x1+y1+1)
D

tensor(0.6464)

In [83]:
loss = Diceloss2D()
ret =loss(x,y)
ret

N_dice_efftensor([0.9411, 4.1337, 0.3457, 0.8258])


tensor(-0.5616)

In [84]:
m = torch.Tensor([[0.5322,0.4932,0.1764],
[0.3107,0.5297,0.1604],
[0.3841,0.3537,0.3574],
[0.3323,0.8301,0.6436]])
m

tensor([[0.5322, 0.4932, 0.1764],
        [0.3107, 0.5297, 0.1604],
        [0.3841, 0.3537, 0.3574],
        [0.3323, 0.8301, 0.6436]])

In [85]:
m_y = torch.Tensor([0,0,0,0,0,0,1,1,1,1,1,1]).reshape(4,3)
m_y

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [86]:
s = m*m_y
t= s.sum()
t

tensor(2.9012)

In [87]:
x =x.sum()
x

tensor(3.9910)

In [88]:
a = m.view(4,-1)
a1 = a.sum(1)
print(a1)
a2= a1.sum()
a2

tensor([1.2018, 1.0008, 1.0952, 1.8060])


tensor(5.1038)

In [89]:
a = m_y.view(4,-1)
a1 = a.sum(1)
print(a1)
a2= a1.sum()
a2

tensor([0., 0., 3., 3.])


tensor(6.)

In [90]:
D=(2*2.9012+1)/(5.1038+6+1)
o =1-D
o

0.4379946793568962

In [91]:
print(m)
print(m_y)
l =loss(m.reshape(1,1,4,3),m_y.reshape(1,1,4,3))
l

tensor([[0.5322, 0.4932, 0.1764],
        [0.3107, 0.5297, 0.1604],
        [0.3841, 0.3537, 0.3574],
        [0.3323, 0.8301, 0.6436]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])
N_dice_efftensor([0.5620])


tensor(0.4380)

In [92]:
import monai
from monai.metrics import DiceMetric
dice_metric = DiceMetric(include_background=True, reduction="mean", get_not_nans=False)
print(m_y)
l1 = dice_metric(m.reshape(1,4,3),m_y.reshape(1,4,3))
print(l1)
 # aggregate the final mean dice result
metric = dice_metric.aggregate().item()
metric

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[   nan,    nan, 0.5349, 0.7516]])


C:\Users\bxd\AppData\Local\Programs\Python\Python39\lib\site-packages\monai\metrics\meandice.py:73: UserWarning: y_pred should be a binarized tensor.
  warnings.warn("y_pred should be a binarized tensor.")


0.6432152986526489

In [93]:
a=[0.5349,0.7516]
t1 = torch.Tensor(a)
t1.sum()/2

tensor(0.6432)

In [106]:
class DiceLossND(nn.Module):
	def __init__(self):
		super().__init__()
	
	def forward(self, input, target):
		"""
			input tesor of shape = (N, C, H, W)
			target tensor of shape = (N, H, W)
		"""
		# 先将 target 进行 one-hot 处理，转换为 (N, C, H, W)
		# nclass = input.shape[1]
		# target = nn.functional.one_hot(target.long(), nclass)

		# print(target.shape)

		assert (input.shape == target.shape, "predict & target shape do not match")
		
		binaryDiceLoss = Diceloss2D()
		total_loss = 0
		
		# 归一化输出
		logits = nn.functional.softmax(input, dim=1)
		C = target.shape[1]
		
		# 遍历 channel，得到每个类别的二分类 DiceLoss
		for i in range(C):
			dice_loss = binaryDiceLoss(logits[:, i], target[:, i])
			total_loss += dice_loss
		
		# 每个类别的平均 dice_loss
		return total_loss / C



<>:16: SyntaxWarning: assertion is always true, perhaps remove parentheses?
<>:16: SyntaxWarning: assertion is always true, perhaps remove parentheses?
C:\Users\bxd\AppData\Local\Temp/ipykernel_13012/910857797.py:16: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (input.shape == target.shape, "predict & target shape do not match")


In [108]:
x =torch.randn((1,3,4,4))
x.shape

torch.Size([1, 3, 4, 4])

In [109]:
y = torch.randint(0,2,(1,3,4,4))
y.shape

torch.Size([1, 3, 4, 4])

In [103]:
x.shape == y.shape

False

In [114]:
loss3d = DiceLossND()
output = loss3d(m.reshape(1,4,3),m_y.reshape(1,4,3))
output

N_dice_efftensor([0.5785])
N_dice_efftensor([0.5964])
N_dice_efftensor([0.5108])
N_dice_efftensor([0.5697])


tensor(0.4362)

In [112]:
# 2D normalized cross correlation, operates on BxRxC arrays
# where B is batch, R is rows, C is columns. Outputs B length
# 1D array of NCC scores for each batch
#
# Copyright (C) 2019-2020 Robert Grupp (grupp@jhu.edu)
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

import torch

def ncc_2d(X,Y):
    N = X.shape[-1] * X.shape[-2]
    assert(N > 1)
    
    #print('X: {}'.format(X.shape))
    #print('Y: {}'.format(Y.shape))

    dim = X.dim()
    d1 = dim - 2
    d2 = dim - 1

    # compute means of each 2D "image"
    mu_X = torch.mean(X, dim=[d1,d2])

    # make the 2D images have zero mean
    X_zm = X - (mu_X.reshape(*mu_X.shape,1,1) * torch.ones_like(X))

    # compute sample standard deviations
    X_sd = torch.sqrt(torch.sum(X_zm * X_zm, dim=[d1,d2]) / (N-1))

    mu_Y = torch.mean(Y, dim=[d1,d2])

    Y_zm = Y - (mu_Y.reshape(*mu_Y.shape,1,1) * torch.ones_like(Y))
    
    Y_sd = torch.sqrt(torch.sum(Y_zm * Y_zm, dim=[d1,d2]) / (N-1))
    
    return torch.sum(X_zm * Y_zm, dim=[d1,d2]) / ((N * (X_sd * Y_sd)) + 1.0e-8)



In [113]:
# Differentiable dice loss
#
# Copyright (C) 2019-2020 Robert Grupp (grupp@jhu.edu)
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

import torch

import torch.nn.modules.loss

class DiceLoss2D(torch.nn.modules.loss._Loss):
    def __init__(self, skip_bg=True):
        super(DiceLoss2D, self).__init__()
        
        self.skip_bg = skip_bg

    def forward(self, input, target):
        # Add this to numerator and denominator to avoid divide by zero when nothing is segmented
        # and ground truth is also empty (denominator term).
        # Also allow a Dice of 1 (-1) for this case (both terms).
        eps = 1.0e-4
        
        if self.skip_bg:
            # numerator of Dice, for each class except class 0 (background)
            # multiply by -2 (usually +2), since we are minimizing the objective function and we want to maximize Dice
            numerators = -2 * torch.sum(torch.sum(target[:,1:,:,:] * input[:,1:,:,:], dim=3), dim=2) + eps

            # denominator of Dice, for each class except class 0 (background)
            denominators = torch.sum(torch.sum(target[:,1:,:,:] * target[:,1:,:,:], dim=3), dim=2) + \
                             torch.sum(torch.sum(input[:,1:,:,:] * input[:,1:,:,:], dim=3), dim=2) + eps

            # minus one to exclude the background class
            num_classes = input.shape[1] - 1
        else:
            # numerator of Dice, for each class
            # multiply by -2 (usually +2), since we are minimizing the objective function and we want to maximize Dice
            numerators = -2 * torch.sum(torch.sum(target[:,:,:,:] * input[:,:,:,:], dim=3), dim=2) + eps

            # denominator of Dice, for each class
            denominators = torch.sum(torch.sum(target[:,:,:,:] * target[:,:,:,:], dim=3), dim=2) + \
                             torch.sum(torch.sum(input[:,:,:,:] * input[:,:,:,:], dim=3), dim=2) + eps
            
            num_classes = input.shape[1]

        # Dice coefficients for each image in the batch, for each class
        dices = numerators / denominators

        # compute average Dice score for each image in the batch
        avg_dices = torch.sum(dices, dim=1) / num_classes
        
        # compute average over the batch
        return torch.mean(avg_dices)

class DiceAndHeatMapLoss2D(torch.nn.modules.loss._Loss):
    def __init__(self, skip_bg=True, heatmap_wgt=0.5):
        super(DiceAndHeatMapLoss2D, self).__init__()
        
        self.dice_loss = DiceLoss2D(skip_bg=skip_bg)
       
        assert((heatmap_wgt > 1.0e-8) and (heatmap_wgt < (1 + 1.0e-8)))
        self.heatmap_wgt = heatmap_wgt
        self.dice_wgt    = 1 - heatmap_wgt

    def forward(self, input, target):
        in_seg      = input[0]
        in_heatmaps = input[1]

        tgt_seg      = target[0]
        tgt_heatmaps = target[1]

        num_lands = tgt_heatmaps.shape[1]

        # L2 Loss
        #hm_errs = (in_heatmaps - tgt_heatmaps).pow(2)
        #avg_hm_errs = torch.sum(torch.sum(torch.sum(hm_errs, dim=3), dim=2), dim=1) / num_lands
        #return self.dice_loss(in_seg, tgt_seg) + (self.heatmap_wgt * torch.mean(avg_hm_errs))
        
        ncc_losses = ncc_2d(in_heatmaps, tgt_heatmaps)
        
        # negation since we are minmizing, normalize output in range [-1,0]
        ncc_losses = (ncc_losses + 1) * -0.5
        
        return (self.dice_wgt * self.dice_loss(in_seg, tgt_seg)) + (self.heatmap_wgt * torch.mean(ncc_losses))
        




In [115]:
print(torch.Tensor)

<class 'torch.Tensor'>


In [116]:
import torch
a = torch.tensor([True,True,False])
print(a.any())
# 打印结果 tensor(True)

b = torch.tensor([False, False, False])
print(b.any())
# 打印结果 tensor(False)


tensor(True)
tensor(False)


In [117]:
import torch
a = torch.tensor([True,True,False])
print(a.all())
# 打印结果 tensor(False)

b = torch.tensor([True,True,True])
print(b.all())
# 打印结果 tensor(True)


tensor(False)
tensor(True)


In [127]:
print(m.byte())
torch.all(m_y.byte() == m_y)



tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)


tensor(True)